korisnik/urls.py
from django.urls import path

from . import views

app_name="korisnik"

urlpatterns = [
    path('',views.home,name='home'),
    path('logged/<str:username>/',views.logged,name= 'logged'),
    path('register/',views.register,name='register'),
    path('redirecting/',views.help,name = 'help'),
    path('logged/<str:username>/adding/' ,views.adding, name='adding'),
    path('redirecting./',views.helpRegister,name='helpRegister'),
    path('logged/<str:username>/delating/',views.delatingRedirecting,name='delatingRedirecting'),
    path('logged/<str:username>/delatingLink/',views.delatingLink,name='delatingLink'),
]

projekat/urls.py
from django.contrib import admin
from django.urls import path,include
from korisnik.views import *
urlpatterns = [
    path("",include("korisnik.urls")),
    path('admin/', admin.site.urls),
]

administrator/models.py
from django.db import models

# Create your models here.

korisnik/models.py
from django.db import models
import time
import urllib.request
from apscheduler.schedulers.background import BackgroundScheduler
from django_apscheduler.jobstores import DjangoJobStore, register_events, register_job
# Create your models here.
from django_apscheduler.models import DjangoJob
from bs4 import BeautifulSoup, Comment
from django.core.mail import send_mail
from django.utils import timezone
from projekat import settings
from datetime import datetime, timedelta

def default_start_time():
    now = datetime.now()
    start = now.replace(year=2000)
    return start


class Korisnik(models.Model):
    username = models.CharField(max_length=20)
    password = models.CharField(max_length=100)
    firstName = models.CharField(max_length=20,default='')
    lastName = models.CharField(max_length = 20,default='')
    email = models.CharField(max_length = 30, default='@')


    def __str__(self):
        return "{}".format(self.username)


class Stranica(models.Model):
    link = models.CharField(max_length=200,default = '')
    korisnik = models.ForeignKey(Korisnik,on_delete=models.CASCADE)
    staroStanje = models.TextField(default='nista')
    posljedniMejl = models.DateTimeField(default=default_start_time)
    def __str__(self):
        return "{}".format(self.link)

class Obavjestenje(models.Model):
    korisnik = models.ForeignKey(Korisnik, on_delete=models.CASCADE)
    naziv = models.CharField(max_length=100)
    sadrzaj = models.CharField(max_length=100)
    datum = models.DateTimeField(null=True)
    def __str__(self):
        return "{}".format(self.naziv)


def tag_visible(element):
    if element.parent.name in ['style', 'script', 'head', 'title', 'meta', '[document]']:
        return False
    if isinstance(element, Comment):
        return False
    return True

try:
    # Instantiated scheduler

    scheduler = BackgroundScheduler()
    # Scheduler uses DjangoJobStore()
    scheduler.add_jobstore(DjangoJobStore(), "default")

    if(len(DjangoJob.objects.all())==0):
        # 'cron' mode loop, Monday to Friday, 9:30:10 every day, id is the work ID as a tag
        # ('scheduler',"interval", seconds=1) # cycle with interval, execute once every second
        #@register_job(scheduler, 'interval',seconds=10)
        @scheduler.scheduled_job('interval',minutes=1)
        def test_job():
            for object in Korisnik.objects.all():
                for stranica in object.stranica_set.all():
                    try:
                        html = urllib.request.urlopen(stranica.link)
                    except:
                         return
                    soup = BeautifulSoup(html, 'html.parser')
                    texts = soup.findAll(text=True)
                    visible_texts = filter(tag_visible, texts)

                    tekst = u" ".join(t.strip() for t in visible_texts)

                    if (stranica.staroStanje == 'nista'):
                        stranica.staroStanje = tekst
                        stranica.save()

                    elif (stranica.staroStanje != tekst):
                        if(stranica.posljedniMejl.year!=2000):

                            brojsekundi = timezone.now()-stranica.posljedniMejl
                            brojminuta  = brojsekundi.total_seconds()/60
                            if(brojminuta<=20):
                                return
                        else :

                            print("Ovo nema obavjestenja jos")
                            pass
                        object.obavjestenje_set.create(naziv="Doslo je do promjene na sajtu", sadrzaj=stranica.link,
                                                         datum=timezone.now())
                        subject = 'Desila se promjena na sajtu'
                        message = ' {} '.format(stranica.link)
                        email_from = settings.EMAIL_HOST_USER
                        recipient_list = ["{}".format(object.email), ]
                        send_mail(subject, message, email_from, recipient_list)
                        stranica.staroStanje = tekst
                        stranica.posljedniMejl=timezone.now()
                        stranica.save()

        register_events(scheduler)
    # Scheduler starts
        scheduler.start()
except Exception as e:
    print(e)

administrator/views.py
from django.shortcuts import render

# Create your views here.

korisnik/views.py
import urllib.request

from background_task import background
from background_task import models
from bs4 import BeautifulSoup, Comment
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone


# Create your views here.
from .models import Korisnik, Stranica






def home(request):
    return render(request, "korisnik/home.html", {})




def adding(request, username):
    objekat = Korisnik.objects.get(username=username)
    try:
        staranica = objekat.stranica_set.get(link=request.POST['link'])
        return HttpResponseRedirect(reverse('korisnik:logged', args=(username,)))
    except:
        pass
    objekat.stranica_set.create(link=request.POST['link'])
    stranica = objekat.stranica_set.get(link=request.POST['link'])




    return HttpResponseRedirect(reverse('korisnik:logged', args=(username,)))


def delatingRedirecting(request, username):
    objekat = Korisnik.objects.get(username=username)
    stranice = objekat.stranica_set.all
    context = {
        'objekat': objekat,
        'stranice': stranice,
        'username': username,
    }
    return render(request, 'korisnik/delating.html', context)


def delatingLink(request, username):
    link = request.POST['stranica']
    objekat = Stranica.objects.get(link=link)
    objekat.delete()
    return HttpResponseRedirect(reverse('korisnik:logged', args=(username,)))


def help(request):
    try:
        username = request.POST['username']
        object = Korisnik.objects.get(username=username)
        if (object.password != request.POST['pwd']):
            return HttpResponseRedirect(reverse('korisnik:home'))
    except(KeyError, Korisnik.DoesNotExist):
        return HttpResponseRedirect(reverse('korisnik:home'))
    return HttpResponseRedirect(reverse('korisnik:logged', args=(object.username,)))


def logged(request, username):
    objekat = Korisnik.objects.get(username=username)
    try:
        print(request.META['HTTP_REFERER'])
    except:
        return HttpResponseRedirect(reverse('korisnik:home'))

    lista = objekat.obavjestenje_set.all()[0:5]
    return render(request, 'korisnik/index.html', {'username': username,
                                                   'objekat': objekat,
                                                   'obavjestenja': lista})


def register(request):
    return render(request, "korisnik/registrationa.html", {})


def helpRegister(request):
    try:
        obj = Korisnik.objects.get(username=request.POST['username'])
        print(obj.username)
        return HttpResponseRedirect(reverse('korisnik:register'))
    except:
        objekat = Korisnik.objects.create(firstName=request.POST['fname'],
                                          lastName=request.POST['lname'],
                                          username=request.POST['username'],
                                          password=request.POST['pwd'],
                                          email=request.POST['email'])
        objekat.save()
        return HttpResponseRedirect(reverse('korisnik:home'))

korisnik/templates/korisnik/delating.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{objekat}}</title>
</head>
<body>
    <form action ="{% url 'korisnik:delatingLink' username %}" method="post">
        {%csrf_token%}
        {% for link in stranice %}

    <input type="radio" id="{{link}}" name = "stranica" value="{{link}}">
    <label for = "{{link}}">{{link}}</label><br>

    {%endfor%}
        <input type="submit" value="Izbrisi link"><br>
    </form>

</body>
</html>

korisnik/templates/korisnik/home.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Untitled</title>
    <link rel="stylesheet" href="{% static 'korisnik/homea/bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'korisnik/homea/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'korisnik/homea/css/Login-Form-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'korisnik/homea/css/styles.css' %}">
</head>

<body>
    <div class="login-dark">
        <form method="post" action="{% url 'korisnik:help'%}">
             {% csrf_token %}
            <h2 class="sr-only">Login Form</h2>
            <div class="illustration"><i class="icon ion-ios-locked-outline"></i></div>
            <div class="form-group"><input class="form-control" type="text" name="username" placeholder="Korisnicko ime"></div>
            <div class="form-group"><input class="form-control" type="password" name="pwd" placeholder="Lozinka"></div>
            <div class="form-group"><button class="btn btn-primary btn-block" type="submit">Prijavi se</button></div>
            <a class="forgot" href="{% url 'korisnik:register' %}">Novi korisnik?</a>
            <a class="forgot" href="#">Zaboravljena lozinka?</a></form>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

korisnik/templates/korisnik/index.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Untitled</title>
    <link rel="stylesheet" href="{% static 'korisnik/assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'korisnik/assets/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'korisnik/assets/css/Features-Boxed.css' %}">
    <link rel="stylesheet" href="{% static 'korisnik/assets/css/Newsletter-Subscription-Form.css' %}">
    <link rel="stylesheet" href="{% static 'korsnik/assets/css/styles.css' %}">
</head>

<body>
    <div class="features-boxed">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">{{username}}</h2>
            </div>
            <div class="row justify-content-center features">
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fa fa-plus icon"></i>
                        <h3 class="name">Dodavanje linkova</h3>
                        <form class="form-inline" method="post" action="{% url 'korisnik:adding' username %}">
                            {%csrf_token%}
                            <div class="form-group"><input class="form-control" type="text" name="link" placeholder="Link"></div>
                            <div class="form-group"><button class="btn btn-primary" type="submit">Dodaj novi link</button></div>
                        </form>
                    </div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fa fa-external-link icon"></i>
                        <h3 class="name">Aktivni linkovi</h3>
                        <form action="{% url 'korisnik:delatingRedirecting' username %}" method="get">
                            {% for stranica in objekat.stranica_set.all %}
                                <a href={{stranica.link}}>{{stranica.link}}</a><br>
                                            {%endfor%}
                            <button class="btn btn-primary" type="submit">Izbrisi link</button></form></div>
                </div>
                <div class="col-sm-6 col-md-5 col-lg-4 item">
                    <div class="box"><i class="fa fa-envelope-o icon"></i>
                        <h3 class="name">Aktivna obavjestenja</h3>
                        {% for obavjestenje in obavjestenja %}

                            <h6>{{obavjestenje.naziv}}</h6>
                        <p>{{obavjestenje.datum}}</p><hr>

    {%endfor%}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>

korisnik/templates/korisnik/logovan.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>{{username}}</title>
     <style type="text/css">

        html,body {
        height: 100%;
            }


     </style>

</head>
<body>
<div class="container-fluid h-100">
    <div class="row justify-content-center h-100">
        <div class="col-4   d-flex justify-content-center align-self-center">
            <div class="">
    <form action="{% url 'korisnik:adding' username %}" method="post">
        {% csrf_token %}
        <label for="link"> Novi link</label>
        <input type="text" id="link" name="link"><br><br>
        <input type="submit" value="Dodaj novi link"><br>
    </form>
            <br>
            <form action="{% url 'korisnik:delatingRedirecting' username %}" method="get">
        <input type = "submit" value = "Brisanje  postojeceg linka">
    </form>
                </div>
        </div>

         <div class="col-4 ">
             <h6> Dodati linkovi za obavjestenja</h6>
    {% for stranica in objekat.stranica_set.all %}
    <a href={{stranica.link}}>{{stranica.link}}</a><br>

    {%endfor%}

            </div>
        <div class="col-4">
    <h6>Obavjestenja</h6>
    {% for obavjestenje in obavjestenja %}

    <br>
    <h3>{{obavjestenje.naziv}}</h3>
    <h4>{{obavjestenje.datum}}</h4>
    <p>{{obavjestenje.sadrzaj}}</p>
    <br><br>
    <hr>

    {%endfor%}
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

korisnik/templates/korisnik/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Registration</title>
     <style type="text/css">

    .center {
        margin: auto;
        width: 50%;
        border: 3px solid blue;
        padding: 70px;
    }
</style>
</head>
<body  class="text-center">
<div class="center" >


<form action="{% url 'korisnik:helpRegister'%}" method="post" >
    {% csrf_token %}
  <label for="fname">First name:</label>  <br>
    <input type ="text" id="fname" name="fname"><br>
    <label for="lname">Last name:</label><br>
    <input type="text" id="lname" name="lname"><br>
  <label for="username">Username:</label><br>
  <input type="text" id="username" name="username"><br>
  <label for="pwd">Password:</label><br>
  <input type="password" id="pwd" name="pwd"><br>
    <label for="email">Email</label><br>
    <input type="text" id="email" name="email"><br><br>
    <input type="submit" value="Registruj se"><br>
    <br>
</form></div>

</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

korisnik/templates/korisnik/registrationa.html
<!DOCTYPE html>
<html>
{%load static%}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Untitled</title>
    <link rel="stylesheet" href="{% static 'korisnik/registration/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static  'korisnik/registration/css/Registration-Form-with-Photo.css' %}">
    <link rel="stylesheet" href="{% static  'korisnik/registration/css/styles.css' %}">
</head>

<body>
    <div class="register-photo">
        <div class="form-container">
            <div class="image-holder"></div>
            <form method="post" action="{% url 'korisnik:helpRegister'%}">
                {% csrf_token %}
                <h2 class="text-center"><strong>Kreiraj</strong> nalog.</h2>
                <div class="form-group"><input class="form-control" type="text" name="fname" placeholder="Ime"></div>
                 <div class="form-group">	<input class="form-control" type="text" name="lname" placeholder="Prezime"></div>
                <div class="form-group"> <input class="form-control" type="text" name="username" placeholder="Korisnicko ime"></div>
                <div
                    class="form-group"><input class="form-control" type="password" name="pwd" placeholder="Lozinka"></div>
        <div class="form-group"><input class="form-control" type="password" name="pwd-repeat" placeholder="Potvrdi lozinku"></div>
        	<div class="form-group"><input class="form-control" type="email" name="email" placeholder="Email"></div>
        <div class="form-group"><button class="btn btn-primary btn-block" type="submit">Registruj se</button></div><a class="already" href="#">Vec imate nalog? Prijavite se ovde</a></form>
    </div>
    </div>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
</body>

</html>